### ISSUE TITLE
Script is broken and probably gets you IP banned

### ISSUE THREAD

**Issue by AnnanFay** [pjf/anki-deck-scraper#3]
I couldn't get this to work. I noticed that the web requests include searches for single letters.

The search as it works right now doesn't return any results unless at least 3 characters are used.

Also, they have implemented throttling so running this script will get you temporarily IP banned.

**Comment by IlanCosman** [comment]
Yah, gets you IP banned. ~~Not sure how long it will last since I haven't gotten unbanned yet 😄~~ EDIT: Lasts one day

@pjf Could you archive this repository and put a warning at the top of the README? If the code no longer works, and it gets you banned, then it seems the responsible thing to do.

**Comment by pjf** [comment]
Oh no. Oh dang. Yes, this should absolutely be archived with a warning. Doing that now!
